use anyhow::{anyhow, Context, Result};
use std::fs;
use std::path::Path;
use std::process::{Command, Stdio};

/// Initialize a git repository in `workspace` if one does not already exist.
///
/// This will run `git init` and create an initial commit of the current
/// contents so that later commits have something to diff against. All git
/// commands are executed in the given directory.  It also sets simple
/// author/committer environment variables to avoid git complaining about
/// missing identity when committing. If git is not available or any
/// command fails, an error is returned.
pub fn init_repo_if_needed(workspace: &Path) -> Result<()> {
    // Ensure the workspace directory exists on disk before running git.
    if !workspace.exists() {
        fs::create_dir_all(workspace)
            .with_context(|| format!("create workspace dir {}", workspace.display()))?;
    }
    // If `.git` already exists we assume the repo is initialized.
    if workspace.join(".git").exists() {
        return Ok(());
    }
    // Run `git init` in the workspace.
    let status = Command::new("git")
        .arg("init")
        .current_dir(workspace)
        .status()
        .with_context(|| "failed to run git init")?;
    if !status.success() {
        return Err(anyhow!("git init failed"));
    }
    // Stage all existing files for the initial commit. Use -A to include
    // ignored/untracked files that were just created.
    let status = Command::new("git")
        .args(&["add", "-A"])
        .current_dir(workspace)
        .status()
        .with_context(|| "failed to run git add in init_repo_if_needed")?;
    if !status.success() {
        return Err(anyhow!("git add failed during initialization"));
    }
    // Perform the initial commit. We set author/committer env vars so git
    // doesn't complain about missing user.name/email.
    let status = Command::new("git")
        .args(&["commit", "-m", "Initial commit"])
        .current_dir(workspace)
        .env("GIT_AUTHOR_NAME", "AutoCoding")
        .env("GIT_AUTHOR_EMAIL", "autocoding@example.com")
        .env("GIT_COMMITTER_NAME", "AutoCoding")
        .env("GIT_COMMITTER_EMAIL", "autocoding@example.com")
        .status()
        .with_context(|| "failed to run git commit during initialization")?;
    // It's okay if commit fails (e.g. nothing to commit) – the next commit
    // will create the first history entry. We don't return an error here.
    let _ = status;
    Ok(())
}

/// Commit all changes in the workspace with a given message.
///
/// Stages every file with `git add -A` and then creates a commit. If there
/// are no changes to commit, the commit command may fail; this function
/// ignores such failures and simply returns Ok(()). Environment variables
/// are set to provide author and committer identities.
pub fn commit_all(workspace: &Path, message: &str) -> Result<()> {
    // Stage all changes.
    let status = Command::new("git")
        .args(&["add", "-A"])
        .current_dir(workspace)
        .status()
        .with_context(|| "failed to run git add in commit_all")?;
    if !status.success() {
        return Err(anyhow!("git add failed"));
    }
    // Commit the changes with provided message. Use env vars for identity.
    let commit_status = Command::new("git")
        .args(&["commit", "-m", message])
        .current_dir(workspace)
        .env("GIT_AUTHOR_NAME", "AutoCoding")
        .env("GIT_AUTHOR_EMAIL", "autocoding@example.com")
        .env("GIT_COMMITTER_NAME", "AutoCoding")
        .env("GIT_COMMITTER_EMAIL", "autocoding@example.com")
        .status()
        .with_context(|| "failed to run git commit in commit_all")?;
    // If there's nothing to commit, git exits with non-zero. We don't treat
    // that as a hard error because it's not harmful – we simply continue.
    let _ = commit_status;
    Ok(())
}

/// Revert the last commit in the workspace.
///
/// This runs `git reset --hard HEAD~1`. If there is only one commit in the
/// repository (for example the initial commit), the command will fail. We
/// ignore such failures and return Ok(()). Any other error (e.g. git not
/// found) will result in an error being returned.
pub fn revert_last_commit(workspace: &Path) -> Result<()> {
    let status = Command::new("git")
        .args(&["reset", "--hard", "HEAD~1"])
        .current_dir(workspace)
        .status()
        .with_context(|| "failed to run git reset --hard")?;
    // If the reset fails (e.g. there is no previous commit), swallow the
    // failure. There's nothing to revert in that case.
    let _ = status;
    Ok(())
}

/// Produce a unified diff of the most recent commit relative to the one
/// immediately before it.
///
/// The diff is generated by running `git diff HEAD~1..HEAD`. If there is
/// no previous commit the diff will be empty. The returned string may be
/// large; callers may wish to truncate it for display purposes. Any errors
/// executing the git command are propagated.
pub fn diff_last_commit(workspace: &Path) -> Result<String> {
    let output = Command::new("git")
        .args(&["diff", "HEAD~1..HEAD"])
        .current_dir(workspace)
        .stdout(Stdio::piped())
        .output()
        .with_context(|| "failed to run git diff")?;
    let diff = String::from_utf8_lossy(&output.stdout).into_owned();
    Ok(diff)
}